### ISSUE TITLE
method naming

### ISSUE THREAD

**Issue by smoebody** [swagger-api/swagger-js#1092]
in v2.x `operationId`'s could have the same name in different paths/controllers. for example:
```yaml
paths:
  /user/{userId}:
    get:
      x-swagger-router-controller: user
        operationId: get
  /group/{groupId}:
    get:
      x-swagger-router-controller: group
        operationId: get
```

results in something like

```javascript
client.user.get(..)
client.group.get(..)
```

now with v3 it results in something like
```javascript
client.apis.user.get1(..)
client.apis.group.get2(..)
```

this is highly unpractical and should be fixed.
