### ISSUE TITLE
Schema reference names clash

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-js#1367]
_From @Gingol on June 13, 2018 8:58_

Hi all,
I'm not sure if it is the right place where report this kind of problem, so please, redirect me to the right project in case I mistake.
During the creation of my specification I obtained a list of errors like this:

> Resolver error
> Cannot read property '0' of undefined

Analyzing the situation I figured out that it was due to the references between the schemas.
This is a simple example of schemas that generate the errors.
```
schemas:
    B:
      type: object
      properties:
        field:
          type: string
    C:
      allOf:
        - $ref: '#/components/schemas/B'
    D:
      allOf:
        - $ref: '#/components/schemas/B'
      type: object
      properties:
        field:
          allOf:
            - $ref: '#/components/schemas/C'
```
Searching online I found some issues regarding circular references and similar, but it seems that all was resolved with a certain version of the editor and I think that mine is a different problem.

I think that the desired output for the schema D would be something like this:
```
{
  field: {
            field: "string"
         }
}
```

Thank you

--
Mauro

_Copied from original issue: swagger-api/swagger-editor#1793_

**Comment by shockey** [comment]
_From @hkosova on June 19, 2018 23:45_

Your example produces the desired output in the latest version of the Swagger Editor at https://editor.swagger.io and does not trigger any errors. But this example does not make sense because schema D is equivalent to
```yaml
    D:
      type: object
      allOf:
        - properties:
            field:
              type: string
        - properties:
            field:
              type: object
              properties:
                field:
                  type: string
```
or the simplified version
```yaml
    D:
      type: object
      properties:
        field:
          allOf:
            - type: string
            - type: object
              properties:
                field:
                  type: string
```
and the top-level `field` property cannot be `type: string` and `type: object` at the same time.
