### ISSUE TITLE
[develop 2.0] Seems to go into recursive infinite loop with recursive 2.0 spec definitions

### ISSUE THREAD

**Issue by gbisaga** [swagger-api/swagger-js#137]
When I bring up a 2.0 definition in the Swagger UI, it seems to go into infinite recursion. This is in Chrome. See open debugger panel in screenshot - note that I added a debug console.log to swagger-client.js line 1010, in the Property.prototype.sampleValue function.

![image](https://cloud.githubusercontent.com/assets/5503641/4404620/53dccf36-44b3-11e4-8b9f-582d6b6fc715.png)

I don't know how to attach a file that has the swagger spec, but here's the relevant bit from the definitions element - let me know if I need to supply more context:

```
definitions:
  psschema.FunctionalArea:
    description: Represents a Functional Areas and all of its sub-areas
    x-version: "1.4.0"
    properties:
      name:
        type: string
        description: Functional area internal name
      display:
        type: string
        description: Functional area display name
      comment:
        type: string
        description: Functional area comment
      subareas:
        type: array
        description: Sub-areas - can be recursive
        items:
          $ref: psschema.FunctionalArea
```
