### ISSUE TITLE
Error 403 does not return json body

### ISSUE THREAD

**Issue by markolofsen** [swagger-api/swagger-js#1427]
### Content & configuration

 Swagger/OpenAPI definition:
 ```yaml
...
        "/api/accounts/login/": {
            "post": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "description": "Endpoint for user login. Returns authentication token on success.",
                "operationId": "accounts_login_create",
                "parameters": [
                    {
                        "description": "",
                        "in": "formData",
                        "name": "email",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "description": "",
                        "in": "formData",
                        "name": "username",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "description": "",
                        "in": "formData",
                        "name": "password",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "201": {
                        "description": ""
                    }
                },
                "summary": "Endpoint for user login. Returns authentication token on success.",
                "tags": [
                    "api"
                ]
            }
        },
...
 ```

 Swagger-Client usage:
 ```js
SwaggerClient({
	url: swaggerUrl,
	v2OperationIdCompatibilityMode: true,
	requestInterceptor: (req) => {

		const auth = new STORAGE().getLocal('auth')
		if (auth) req.headers.Authorization = `Token ${auth.token}`

		return req
	}.then(client => {
		client.apis.api.accounts_login_create({
				email: '1@1.ru, password: '
				123456 '
			})
			.then(res => {
				// there is a problem, error 403 is not returned
        
				const { token } = res.body
				new STORAGE().setLocal('auth', {
					token
				})
        
			})
			.catch(err => console.warn(err))

	}).catch(err => err)

})
 ```

### Is your feature request related to a problem?

Can't get request body when server responding with 403 header.

### Describe the solution you'd like
No solutions...
