### ISSUE TITLE
parameter builder uses a comma instead of an empty string

### ISSUE THREAD

**Issue by encodeering** [swagger-api/swagger-js#1708]
Hello,

it seems that an additional `,` can appended to the path in some cases and it has been detected using swagger ui's execution feature (swagger-ui-dist@3.32.5). It could be traced back to the following line:

https://github.com/swagger-api/swagger-js/blob/3627eadb1387975c6d7afae766d27e6cb286b846/src/execute/oas3/parameter-builders.js#L26

The default behavior of [Array.join](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join) will be used if `styledValue` is `undefined`.

The following yaml definition creates this case, if the input field in swagger ui remains untouched

```
paths:
  /openapi/specification{plural}:
    parameters:
    - name: plural
      in: path
      required: false
      schema:
        type: string
        pattern: "s?
```

Many thanks in advance.
