### ISSUE TITLE
$ref: object property is treated as a reference

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/swagger-js#1719]
### Q&A (please complete the following information)
 - OS:  any
 - Environment: any
 - Method of installation: [e.g. npm, unpkg]
 - Swagger-Client version: 3.10.12
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Swagger/OpenAPI definition:
```yaml
LocalReferenceById:
      type: object
      properties:
        $ref:
          type: string
```

where `LocalReferenceById` is defined as part of `anyOf`

```
Contact_orReference:
      anyOf:
        - $ref: '#/components/schemas/LocalReferenceById'
        - $ref: '#/components/schemas/Contact_referenceable'
```

full yaml

### To reproduce...

1. Load attached yaml into swagger-ui or swagger-editor
2. Expand the `throwError` operation
3. "e.split is not a function"

### Expected behavior

SwaggerClient should not try to continue generating absolute reference. Instead, should treat `$ref` as a property.
