### ISSUE TITLE
How to set server variables when initializing the SwaggerClient

### ISSUE THREAD

**Issue by vithu30** [swagger-api/swagger-js#1808]
### Q&A (please complete the following information)
How can I set the server variables when initializing the SwaggerClient. Is there any possibility to do that? The server definition in OAS is given below:

Swagger/OpenAPI definition:
```yaml
- url: '{scheme}://{host}/rest/client/v1'
  variables:
    scheme:
      default: https
      enum:
        - http
        - https
    host:
      default: rest.apis.com
```

I want to override the host name when initializing the Swagger-Client. Is there any way to set server variables to resolve the parameterized server URLs.

Swagger-Client usage:
```js
SwaggerClient({
  spec,
   requestInterceptor,
   responseInterceptor,
})
```
