### ISSUE TITLE
Problem with array of object for body param

### ISSUE THREAD

**Issue by GiladShoham** [swagger-api/swagger-js#610]
Hi,
I have tried to add body param that get an array of my objects.
(something like the body in http://petstore.swagger.io/#/ -  POST /user/createWithArray)

i have tried to remove the ref and put the object scheme right inside (my json-ref resolver make it automatically):
```yaml
- in: body
        description: Array of something
        name: myArr
        required: true
        schema:
          type: array
          items:
            type: object
            properties:
              myProp:
                type: string
```
This didn't worked (i saw in swagger-ui that it's array[undefined] 
and i saw an error in the server that 
Cannot read property 'schema' of undefined

i found very strange behavior, when i change the items back to be $ref for the same object is working, i mean:
```yaml
- in: body
        description: Array of something
        name: myArr
        required: true
        schema:
          $ref: '#/definitions/myObj'
```
and my obj (under definition) is something like:
```yaml
myObj:
  type: object
  properties:
    myProp:
      type: string
```
is working.
but this should be exactly the same.

This behavior make it very hard for me because i use my code (taken from here:
http://azimi.me/2015/07/16/split-swagger-into-smaller-files.html)
to resolve all the $ref to be one json instead of let the swagger itself to do it.
so now i somehow need to change it to not resolve only in specific case:
when it's array under parameters under body type param

also this is only working for swagger ui but in the server i still get an error of 
Cannot read property 'schema' of undefined
so i still can't use it
