### ISSUE TITLE
Incorrect absolute paths resolutions in $ref

### ISSUE THREAD

**Issue by PavelPolyakov** [swagger-api/swagger-js#695]
Hi,

As I was told by @webron and @fehguy  - this is the best place for the issue like this.
It all started from this issue, though:
https://github.com/swagger-api/swagger-ui/issues/1878#issuecomment-172471293

The issue is the next, when you reference another ```yaml``` file like this:
```yaml
definitions:
  NewCustomer:
    $ref: /definitions/NewCustomer.yaml
```

it doesn't resolved right, assuming that the file from which you are referencing is located not on the top level directory.

Here is the repository with the example to reproduce:
https://github.com/PavelPolyakov/swagger-ui-refs

Let me know, if you need anything from my side.

Regards,
